apiVersion: apps/v1
kind: Deployment

metadata:
  name: javak8s:v1

spec:

  replicas: 2

  selector:
    matchLabels:
      app: javak8s:v1

  template:

    metadata:
      labels:
        app: javak8s:v1

    spec:

      containers:

        - name: javak8s:v1

          image: brahma999/javak8s:v1

          ports:
            - containerPort: 8080

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "512Mi"
              cpu: "500m"